CMS_HOST: studio.alrafi.org
CMS_OAUTH2_SECRET: <REDACTED_FOR_SECURITY>
CONTACT_EMAIL:contact@alrafi.org
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false
ID: <REDACTED_FOR_SECURITY>
JWT_RSA_PRIVATE_KEY: <REDACTED_FOR_SECURITY>

LANGUAGE_CODE: en
LMS_HOST: lms.alrafi.org

MEILISEARCH_API_KEY: <REDACTED_FOR_SECURITY>
MEILISEARCH_API_KEY_UID: <REDACTED_FOR_SECURITY>
MEILISEARCH_MASTER_KEY: <REDACTED_FOR_SECURITY>

MONGODB_HOST: openedx-mongo.cluster-czeggmy8a2oc.us-east-2.docdb.amazonaws.com
MONGODB_PASSWORD: <REDACTED_FOR_SECURITY>
MONGODB_PORT: 27017
MONGODB_USERNAME: openedx

MYSQL_HOST: openedx.czeggmy8a2oc.us-east-2.rds.amazonaws.com
MYSQL_ROOT_PASSWORD: <REDACTED_FOR_SECURITY>
MYSQL_ROOT_USERNAME: admin
OPENEDX_MYSQL_DATABASE: openedx
OPENEDX_MYSQL_PASSWORD: <REDACTED_FOR_SECURITY>
OPENEDX_MYSQL_USERNAME: admin

OPENEDX_SECRET_KEY: <REDACTED_FOR_SECURITY>

PLATFORM_NAME: Al-Rafi

PLUGINS:
- docdb_fix
- indigo
- mfe

PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib

REDIS_HOST: openedx-redis.mqtg7r.ng.0001.use2.cache.amazonaws.com
REDIS_PORT: 6379

RUN_ELASTICSEARCH: false
RUN_MEILISEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false

SMTP_HOST: smtp.gmail.com
SMTP_PASSWORD: <REDACTED_FOR_SECURITY>
SMTP_PORT: 587
SMTP_USERNAME: <REDACTED_FOR_SECURITY>
SMTP_USE_SSL: false
SMTP_USE_TLS: true
